# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('time_periods', '__first__'),
        ('tasks', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='allocation', help_text='The base type of this resource.', max_length=50)),
                ('effort_allocation', models.FloatField(blank=True, help_text='The effort allocation in hours.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(help_text='The task this allocation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='tasks.task')),
                ('time_period', models.ForeignKey(help_text='The time period this allocation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='time_periods.timeperiod')),
                ('user', models.ForeignKey(help_text='The user this allocation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='users.user')),
            ],
            options={
                'db_table': 'allocations',
                'ordering': ['-created_at'],
                'unique_together': {('task', 'user', 'time_period')},
            },
        ),
    ]
