# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='audit_log_event', help_text='The base type of this resource.', max_length=50)),
                ('action', models.CharField(choices=[('created', 'Created'), ('deleted', 'Deleted'), ('changed', 'Changed'), ('added', 'Added'), ('removed', 'Removed')], help_text='The type of action taken.', max_length=50)),
                ('actor', models.JSONField(blank=True, help_text='The user or application that triggered the event.', null=True)),
                ('context', models.JSONField(blank=True, help_text='The context of the event.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time at which this event occurred.')),
                ('details', models.JSONField(blank=True, help_text='The details of the event.', null=True)),
                ('resource', models.JSONField(blank=True, help_text='The resource that was affected.', null=True)),
            ],
            options={
                'db_table': 'audit_log_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
