# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='membership', help_text='The base type of this resource.', max_length=50)),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('editor', 'Editor'), ('commenter', 'Commenter'), ('viewer', 'Viewer')], help_text='The role of the user in the membership.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(blank=True, help_text='The goal in the membership.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_memberships', to='goals.goal')),
            ],
            options={
                'db_table': 'memberships',
                'ordering': ['-created_at'],
            },
        ),
    ]
