# Generated by Django 4.2.27 on 2026-01-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='portfolio',
            field=models.ForeignKey(blank=True, help_text='The portfolio in the membership.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_memberships', to='portfolios.portfolio'),
        ),
    ]
