# Generated by Django 4.2.27 on 2026-01-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0002_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project in the membership.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_memberships', to='projects.project'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(help_text='The user in the membership.', on_delete=django.db.models.deletion.CASCADE, related_name='generic_memberships', to='users.user'),
        ),
    ]
