# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='project_brief', help_text='The base type of this resource.', max_length=50)),
                ('title', models.CharField(blank=True, help_text='The title of the project brief.', max_length=500, null=True)),
                ('html_text', models.TextField(blank=True, help_text='HTML formatted text for the project brief.', null=True)),
                ('text', models.TextField(blank=True, help_text='Plain text of the project brief.', null=True)),
                ('permalink_url', models.URLField(blank=True, help_text='A url that points directly to the object within Asana.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_briefs',
                'ordering': ['-created_at'],
            },
        ),
    ]
