# Generated by Django 4.2.27 on 2026-01-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('project_briefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbrief',
            name='project',
            field=models.OneToOneField(help_text='The project this brief belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='project_brief', to='projects.project'),
        ),
    ]
