# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_statuses', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='project', help_text='The base type of this resource.', max_length=50)),
                ('name', models.CharField(help_text='Name of the project.', max_length=255)),
                ('archived', models.BooleanField(default=False, help_text='Whether the project is archived.')),
                ('color', models.CharField(blank=True, choices=[('dark-pink', 'Dark Pink'), ('dark-green', 'Dark Green'), ('dark-blue', 'Dark Blue'), ('dark-red', 'Dark Red'), ('dark-teal', 'Dark Teal'), ('dark-brown', 'Dark Brown'), ('dark-orange', 'Dark Orange'), ('dark-purple', 'Dark Purple'), ('dark-warm-gray', 'Dark Warm Gray'), ('light-pink', 'Light Pink'), ('light-green', 'Light Green'), ('light-blue', 'Light Blue'), ('light-red', 'Light Red'), ('light-teal', 'Light Teal'), ('light-brown', 'Light Brown'), ('light-orange', 'Light Orange'), ('light-purple', 'Light Purple'), ('light-warm-gray', 'Light Warm Gray')], help_text='Color of the project.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time at which this resource was created.')),
                ('due_date', models.DateField(blank=True, help_text='The day on which this project is due.', null=True)),
                ('due_on', models.DateField(blank=True, help_text='The day on which this project is due.', null=True)),
                ('html_notes', models.TextField(blank=True, help_text='The notes of the project with formatting as HTML.', null=True)),
                ('is_template', models.BooleanField(default=False, help_text='Whether this project is a template.')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='The time at which this project was last modified.')),
                ('notes', models.TextField(blank=True, help_text='Free-form textual information associated with the project.', null=True)),
                ('public', models.BooleanField(default=False, help_text='True if the project is public to its team.')),
                ('start_on', models.DateField(blank=True, help_text='The day on which work for this project begins.', null=True)),
                ('current_status', models.ForeignKey(blank=True, help_text='Current status of the project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project_statuses.projectstatus')),
                ('workspace', models.ForeignKey(help_text='The workspace or organization this project is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['name'],
            },
        ),
    ]
