# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='workspace', help_text='The base type of this resource.', max_length=50)),
                ('name', models.CharField(blank=True, help_text='The name of the workspace.', max_length=255, null=True)),
                ('email_domains', models.JSONField(blank=True, default=list, help_text='The email domains that are associated with this workspace.', null=True)),
                ('is_organization', models.BooleanField(blank=True, default=False, help_text='Whether the workspace is an *organization*.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspaces',
                'ordering': ['name'],
            },
        ),
    ]
