# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='custom_field', help_text='The base type of this resource.', max_length=50)),
                ('name', models.CharField(help_text='The name of the custom field.', max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('enum', 'Enum'), ('multi_enum', 'Multi Enum'), ('number', 'Number'), ('date', 'Date'), ('people', 'People'), ('formula', 'Formula')], help_text='The type of the custom field.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='The description of the custom field.', null=True)),
                ('enabled', models.BooleanField(default=True, help_text='Whether the custom field is enabled.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(help_text='The workspace this custom field belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'custom_fields',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldEnumOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource.', max_length=255, unique=True)),
                ('name', models.CharField(help_text='The name of the enum option.', max_length=255)),
                ('enabled', models.BooleanField(default=True, help_text='Whether the enum option is enabled.')),
                ('color', models.CharField(blank=True, help_text='Color of the enum option.', max_length=50, null=True)),
                ('custom_field', models.ForeignKey(help_text='The custom field this option belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='enum_options', to='custom_fields.customfield')),
                ('insert_after', models.ForeignKey(blank=True, help_text='The enum option to insert after.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inserted_before', to='custom_fields.customfieldenumoption')),
                ('insert_before', models.ForeignKey(blank=True, help_text='The enum option to insert before.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inserted_after', to='custom_fields.customfieldenumoption')),
            ],
            options={
                'db_table': 'custom_field_enum_options',
                'ordering': ['name'],
            },
        ),
    ]
