# Generated by Django 4.2.27 on 2026-01-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        ('portfolio_memberships', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomembership',
            name='portfolio',
            field=models.ForeignKey(help_text='The portfolio in the membership.', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_memberships', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='portfoliomembership',
            name='user',
            field=models.ForeignKey(help_text='The user in the membership.', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_memberships', to='users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliomembership',
            unique_together={('portfolio', 'user')},
        ),
    ]
