# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        ('users', '0001_initial'),
        ('time_periods', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='goal', help_text='The base type of this resource.', max_length=50)),
                ('name', models.CharField(help_text='The name of the goal.', max_length=500)),
                ('notes', models.TextField(blank=True, help_text='Free-form textual information associated with the goal.', null=True)),
                ('html_notes', models.TextField(blank=True, help_text='The notes of the goal with formatting as HTML.', null=True)),
                ('due_on', models.DateField(blank=True, help_text='The localized day on which this goal is due.', null=True)),
                ('start_on', models.DateField(blank=True, help_text='The day on which work for this goal begins.', null=True)),
                ('is_workspace_level', models.BooleanField(default=False, help_text='Whether this goal is a workspace-level goal.')),
                ('liked', models.BooleanField(default=False, help_text='True if the goal is liked by the authorized user.')),
                ('status', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', help_text='The current status of this goal.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='The owner of the goal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_goals', to='users.user')),
                ('time_period', models.ForeignKey(blank=True, help_text='The time period this goal belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='time_periods.timeperiod')),
                ('workspace', models.ForeignKey(help_text='The workspace this goal belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'goals',
                'ordering': ['name'],
            },
        ),
    ]
