# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='attachment', help_text='The base type of this resource.', max_length=50)),
                ('name', models.CharField(help_text='The name of the file.', max_length=500)),
                ('resource_subtype', models.CharField(blank=True, help_text='The service hosting the attachment.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time at which this resource was created.')),
                ('download_url', models.URLField(blank=True, help_text='The URL containing the content of the attachment.', null=True)),
                ('host', models.CharField(blank=True, help_text='The service hosting the attachment.', max_length=100, null=True)),
                ('permanent_url', models.URLField(blank=True, help_text='The service hosting the attachment.', null=True)),
                ('view_url', models.URLField(blank=True, help_text='The URL where the attachment can be viewed.', null=True)),
                ('size', models.BigIntegerField(blank=True, help_text='The size of the attachment in bytes.', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created the attachment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments_created', to='users.user')),
                ('parent', models.ForeignKey(help_text='The task this attachment is attached to.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
