# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='custom_type', help_text='The base type of this resource.', max_length=50)),
                ('name', models.CharField(help_text='The name of the custom type.', max_length=255)),
                ('enabled', models.BooleanField(default=True, help_text='Whether the custom type is enabled.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(help_text='The workspace this custom type belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_types', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'custom_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomTypeStatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource.', max_length=255, unique=True)),
                ('name', models.CharField(help_text='The name of the status option.', max_length=255)),
                ('enabled', models.BooleanField(default=True, help_text='Whether the status option is enabled.')),
                ('color', models.CharField(blank=True, help_text='Color of the status option.', max_length=50, null=True)),
                ('custom_type', models.ForeignKey(help_text='The custom type this status option belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='status_options', to='custom_types.customtype')),
            ],
            options={
                'db_table': 'custom_type_status_options',
                'ordering': ['name'],
            },
        ),
    ]
