# Generated by Django 4.2.27 on 2026-01-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('tasks', '__first__'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='new_project',
            field=models.ForeignKey(blank=True, help_text='The new project created by this job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='job',
            name='new_task',
            field=models.ForeignKey(blank=True, help_text='The new task created by this job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='tasks.task'),
        ),
    ]
