# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='project_status', help_text='The base type of this resource.', max_length=50)),
                ('title', models.CharField(help_text='The title of the project status update.', max_length=255)),
                ('text', models.TextField(help_text='The text content of the status update.')),
                ('html_text', models.TextField(blank=True, help_text='The text content of the status update with formatting as HTML.', null=True)),
                ('color', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue')], help_text='The color associated with the status update.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time at which this resource was created.')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='The time at which this project status was last modified.')),
                ('author', models.ForeignKey(blank=True, help_text='The user who created the status update.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_statuses', to='users.user')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created the status update.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_statuses_created', to='users.user')),
            ],
            options={
                'db_table': 'project_statuses',
                'ordering': ['-created_at'],
            },
        ),
    ]
