# Generated by Django 4.2.27 on 2026-01-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_statuses', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this status update belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='projects.project'),
        ),
    ]
