# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='organization_export', help_text='The base type of this resource.', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='The status of the organization export.', max_length=50)),
                ('download_url', models.URLField(blank=True, help_text='The URL to download the export.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='The organization/workspace this export belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='organization_exports', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'organization_exports',
                'ordering': ['-created_at'],
            },
        ),
    ]
