# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='project_membership', help_text='The base type of this resource.', max_length=50)),
                ('write_access', models.CharField(blank=True, choices=[('full_write', 'Full Write'), ('comment_only', 'Comment Only')], help_text='Whether the user has full access to the project or comment-only access.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_memberships',
                'ordering': ['-created_at'],
            },
        ),
    ]
