# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoalRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='goal_relationship', help_text='The base type of this resource.', max_length=50)),
                ('contribution_weight', models.FloatField(blank=True, help_text="The weight that the supporting resource's progress contributes to the supported goal.", null=True)),
                ('supporting_resource', models.JSONField(blank=True, help_text='The supporting resource that contributes to the goal.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'goal_relationships',
                'ordering': ['-created_at'],
            },
        ),
    ]
