# Generated by Django 4.2.27 on 2026-01-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goal_relationships', '0001_initial'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalrelationship',
            name='supported_goal',
            field=models.ForeignKey(help_text='The goal that is being supported.', on_delete=django.db.models.deletion.CASCADE, related_name='goal_relationships', to='goals.goal'),
        ),
    ]
