# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='event', help_text='The base type of this resource.', max_length=50)),
                ('action', models.CharField(choices=[('added', 'Added'), ('changed', 'Changed'), ('deleted', 'Deleted'), ('undeleted', 'Undeleted')], help_text='The type of action taken on the resource.', max_length=50)),
                ('resource', models.JSONField(help_text='The resource that triggered the event.')),
                ('parent', models.JSONField(blank=True, help_text='The parent of the resource, if applicable.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time at which this event occurred.')),
                ('user', models.ForeignKey(blank=True, help_text='The user who triggered the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='users.user')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-created_at'],
            },
        ),
    ]
