# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('actions', models.JSONField(help_text='Array of actions to perform.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'batch_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField(help_text='Array of responses from the batch request.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_request', models.OneToOneField(help_text='The batch request this response belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='batch_response', to='batch.batchrequest')),
            ],
            options={
                'db_table': 'batch_responses',
            },
        ),
    ]
