# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='custom_field_setting', help_text='The base type of this resource.', max_length=50)),
                ('is_important', models.BooleanField(default=False, help_text='Whether this field should be shown on the task card.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_field', models.ForeignKey(help_text='The custom field in the setting.', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='custom_fields.customfield')),
            ],
            options={
                'db_table': 'custom_field_settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
