# Generated by Django 4.2.27 on 2026-01-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_field_settings', '0002_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldsetting',
            name='portfolio',
            field=models.ForeignKey(blank=True, help_text='The portfolio this custom field setting belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_settings', to='portfolios.portfolio'),
        ),
    ]
