# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='budget', help_text='The base type of this resource.', max_length=50)),
                ('name', models.CharField(help_text='The name of the budget.', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='The amount of the budget.', max_digits=15, null=True)),
                ('currency_code', models.CharField(blank=True, help_text='The currency code of the budget.', max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['name'],
            },
        ),
    ]
