# Generated by Django 4.2.27 on 2026-01-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(help_text='The project this budget belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='projects.project'),
        ),
    ]
