# Generated by Django 4.2.27 on 2026-01-15 13:02

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(default=common.models.generate_gid, help_text='Globally unique identifier of the resource, as a string.', max_length=255, unique=True)),
                ('resource_type', models.CharField(default='portfolio', help_text='The base type of this resource.', max_length=50)),
                ('name', models.CharField(help_text='The name of the portfolio.', max_length=255)),
                ('archived', models.BooleanField(default=False, help_text='True if the portfolio is archived.')),
                ('color', models.CharField(blank=True, choices=[('dark-pink', 'Dark Pink'), ('dark-green', 'Dark Green'), ('dark-blue', 'Dark Blue'), ('dark-red', 'Dark Red'), ('dark-teal', 'Dark Teal'), ('dark-brown', 'Dark Brown'), ('dark-orange', 'Dark Orange'), ('dark-purple', 'Dark Purple'), ('dark-warm-gray', 'Dark Warm Gray'), ('light-pink', 'Light Pink'), ('light-green', 'Light Green'), ('light-blue', 'Light Blue'), ('light-red', 'Light Red'), ('light-teal', 'Light Teal'), ('light-brown', 'Light Brown'), ('light-orange', 'Light Orange'), ('light-purple', 'Light Purple'), ('light-warm-gray', 'Light Warm Gray')], help_text='Color of the portfolio.', max_length=50, null=True)),
                ('start_on', models.DateField(blank=True, help_text='The day on which work for this portfolio begins.', null=True)),
                ('due_on', models.DateField(blank=True, help_text='The day on which this portfolio is due.', null=True)),
                ('default_access_level', models.CharField(blank=True, choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], help_text='The default access level when inviting new members.', max_length=50, null=True)),
                ('privacy_setting', models.CharField(blank=True, choices=[('public_to_domain', 'Public To Domain'), ('members_only', 'Members Only')], help_text='The privacy setting of the portfolio.', max_length=50, null=True)),
                ('public', models.BooleanField(default=False, help_text='True if the portfolio is public to its workspace members.')),
                ('permalink_url', models.URLField(blank=True, help_text='A url that points directly to the object within Asana.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'portfolios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_projects', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'portfolio_projects',
            },
        ),
    ]
