# Generated by Django 4.2.27 on 2026-01-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_portfolios', to='projects.project'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created the portfolio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios_created', to='users.user'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The owner of the portfolio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_portfolios', to='users.user'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='workspace',
            field=models.ForeignKey(help_text='The workspace this portfolio belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='workspaces.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioproject',
            unique_together={('portfolio', 'project')},
        ),
    ]
